# Shamelessly copied from (and slightly adapted): https://github.com/smartb-energy/docker-python/blob/master/.travis.yml

sudo: required

language: ruby

services:  
    - docker

before_install:  
    - cd test/rspec-based
    - bundle install --path ./vendor/bundle

script:  
    - bundle exec rspec
